In [1]:
print('hii'+'helo')

hiihelo


In [2]:
16/3

5.333333333333333

In [3]:
def a(afk):
    r=afk+5
    return 'hii'
    return r

a(2)

'hii'

In [4]:
even=[1,2,3,4,5,6]
for i in even:
    print(i,sep="  ",end="")

123456

In [5]:
"halp"[-1::-1]

'plah'

In [6]:
import collections as cl

a='abbbbbaacccc'

m=cl.Counter(a)
print(tuple(m.elements()))

('a', 'a', 'a', 'b', 'b', 'b', 'b', 'b', 'c', 'c', 'c', 'c')


In [7]:
import datetime as dt

x=dt.datetime.now()
print(x)
print(dt.datetime(2020,12,12))
print(x.strftime('%Y'))


2025-03-24 01:35:51.990344
2020-12-12 00:00:00
2025


In [8]:
import numpy as np

a=np.array([[1,2,3],[4,5,4]])
print(a)
print(type(a))
a.ndim  #get dimension

[[1 2 3]
 [4 5 4]]
<class 'numpy.ndarray'>


2

In [9]:
a.dtype

dtype('int32')

In [10]:
a.shape

(2, 3)

In [11]:
a.size

6

In [12]:
a.itemsize

4

In [13]:
a.nbytes

24

In [14]:
a[0,1]

2

In [15]:
a[0,-2]

2

In [16]:
a[:1:]

array([[1, 2, 3]])

In [17]:
a[::-1]

array([[4, 5, 4],
       [1, 2, 3]])

In [18]:
a[0,:]

array([1, 2, 3])

In [19]:
a[:,1]

array([2, 5])

In [20]:
a[:,1]=0
print(a)

[[1 0 3]
 [4 0 4]]


In [21]:
a[:,1]=[9,9]
print(a)

[[1 9 3]
 [4 9 4]]


In [22]:
np.zeros((1,2,6))

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [23]:
np.ones((4),dtype='int32')

array([1, 1, 1, 1])

In [24]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
np.full((2,3),33,dtype='float32')

array([[33., 33., 33.],
       [33., 33., 33.]], dtype=float32)

In [26]:
np.full_like(a,4)

array([[4, 4, 4],
       [4, 4, 4]])

In [27]:
np.random.rand(2,3,1)

array([[[0.046753  ],
        [0.29186167],
        [0.25801491]],

       [[0.29731502],
        [0.45964769],
        [0.275118  ]]])

In [28]:
np.random.randint(2,5,size=(2,3))

array([[2, 3, 3],
       [4, 2, 4]])

In [29]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
arr=np.array([[1,2,3]])
np.repeat(arr,4)
#arr.shape

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [31]:
np.repeat(arr,4,axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [32]:
a=np.ones((2,3))

In [33]:
b=np.full((3,3),3)

In [34]:
np.matmul(a,b)

array([[9., 9., 9.],
       [9., 9., 9.]])

In [35]:
c=np.identity(5)

In [36]:
np.linalg.det(c)   #determinant

1.0

In [37]:
r=np.array([[2,4,5],[7,1,2]])

In [38]:
np.min(r)

1

In [39]:
np.max(r)

7

In [40]:
np.min(r,axis=1)

array([2, 1])

In [41]:
np.min(r,axis=0)

array([2, 1, 2])

In [42]:
np.sum(r)

21

In [43]:
np.sum(r,axis=0)

array([9, 5, 7])

In [44]:
np.sum(r,axis=1)

array([11, 10])

In [45]:
r.reshape(3,1,2)

array([[[2, 4]],

       [[5, 7]],

       [[1, 2]]])

In [46]:
v1=np.array([2,4,6])
v2=np.array([6,8,1])
np.vstack([v1,v2,v2])

array([[2, 4, 6],
       [6, 8, 1],
       [6, 8, 1]])

In [47]:
q=np.hstack([v1,v2,v1])
q[[2,3,7]]
q>4
q[q>4]

array([6, 6, 8, 6])

In [48]:
v3=np.full((2,3),3)
v4=np.ones((2,2))
np.hstack((v4,v3))

array([[1., 1., 3., 3., 3.],
       [1., 1., 3., 3., 3.]])

In [49]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [50]:
arr=np.array([1,2,3])
arr.reshape(1,3)

array([[1, 2, 3]])

In [51]:
arr[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [52]:
arr[np.newaxis,:]

array([[1, 2, 3]])

In [53]:
x=[1,2,3]
y=[4,2,3]
np.concatenate([x,y])

array([1, 2, 3, 4, 2, 3])

In [54]:
st=np.concatenate([[x,y]])
st

array([[1, 2, 3],
       [4, 2, 3]])

In [55]:
np.concatenate([st,st],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 2, 3, 4, 2, 3]])

In [56]:
np.sin(np.pi)

1.2246467991473532e-16

In [57]:
np.linspace(0,90,5)

array([ 0. , 22.5, 45. , 67.5, 90. ])

In [58]:
np.exp2([1,2,3])

array([2., 4., 8.])

In [59]:
np.power(3,2)

9

In [60]:
np.log(np.exp(1))

1.0

In [61]:
np.log10(10)

1.0

In [62]:
x=[1,2,3]
np.log2(x)

array([0.       , 1.       , 1.5849625])

In [63]:
x=np.empty([2,3])
y=np.arange(5)

In [64]:
x=np.arange(1,6)
np.add.reduce(x)

15

In [65]:
np.multiply.reduce(x)


120

In [66]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [67]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

In [68]:
np.multiply.outer(x,x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [69]:
np.add.outer(x,x)

array([[ 2,  3,  4,  5,  6],
       [ 3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10]])

In [70]:
np.random.randint(10,15,size=4)

array([11, 14, 14, 11])

In [71]:
x=np.random.rand(3)
x

array([0.08633861, 0.01050675, 0.29949523])

In [72]:
%timeit x.sum()

1.26 μs ± 78.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [73]:
%timeit np.sum(x)

2.23 μs ± 107 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [74]:
x.min()

0.010506750849778701

In [75]:
np.min(x)

0.010506750849778701

In [76]:
import numpy as np
y=np.random.rand(2,4)
y

array([[0.3443995 , 0.73887528, 0.90282736, 0.60252406],
       [0.11134418, 0.57895045, 0.25246887, 0.37011499]])

In [77]:
np.min(y,axis=0)

array([0.11134418, 0.57895045, 0.25246887, 0.37011499])

In [78]:
y.mean()

0.48768808776163086

In [79]:
y.std()

0.24704999649284345

In [80]:
np.percentile(y,50)

0.47453272418599884

In [81]:
np.median(y)

0.47453272418599884

In [82]:
np.ones((3,3),dtype='int')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [83]:
nn=np.ones((3,3),dtype='int') + np.arange(3)[:,np.newaxis] 

In [84]:
a=nn.mean(0)    #axis=0

In [85]:
nn-a #centering

array([[-1., -1., -1.],
       [ 0.,  0.,  0.],
       [ 1.,  1.,  1.]])

In [86]:
x=np.linspace(0,13,50)
y=np.linspace(0,9,20)[:,np.newaxis]


In [87]:
z=np.sin(x)**13+np.cos(x)+np.exp(np.tan(y))**np.cos(y)
z

array([[ 2.00000000e+00,  1.96501231e+00,  1.86264017e+00,
         1.71227857e+00,  1.65875943e+00,  1.91771935e+00,
         1.97608753e+00,  1.30006006e+00,  5.99914981e-01,
         2.78166251e-01,  1.17030552e-01,  2.48114859e-02,
         8.85266882e-04,  4.68723672e-02,  1.59207864e-01,
         3.09904940e-01,  3.20695801e-01,  3.39316676e-02,
         8.86614960e-02,  8.32921543e-01,  1.47231494e+00,
         1.75327741e+00,  1.90196716e+00,  1.98363815e+00,
         1.99646050e+00,  1.93955597e+00,  1.81768565e+00,
         1.67098700e+00,  1.70981331e+00,  2.00533859e+00,
         1.82545614e+00,  1.03903228e+00,  4.65385853e-01,
         2.18008328e-01,  8.06548864e-02,  9.65378018e-03,
         7.95800034e-03,  7.56771563e-02,  2.06442244e-01,
         3.43623208e-01,  2.50479576e-01, -3.09930041e-02,
         2.78706444e-01,  1.08096785e+00,  1.58831998e+00,
         1.80845523e+00,  1.93508663e+00,  1.99530085e+00,
         1.98586706e+00,  1.90745950e+00],
       [ 2.57

In [88]:
c=np.array([1,2,3,4,5,6])
c>3

array([False, False, False,  True,  True,  True])

In [89]:
(c>3) & (c<5)    #use bitwise logic here

array([False, False, False,  True, False, False])

In [90]:
np.where(c>3,1,0)

array([0, 0, 0, 1, 1, 1])

In [91]:
np.count_nonzero(c>3)

3

In [92]:
np.sum(c>3)

3

In [93]:
np.any(c>3)

True

In [94]:
np.all(c>3)

False

In [95]:
c[c>3]

array([4, 5, 6])